
name: 'Thank You Action'
description: 'Say "Stay hard- WORK HARD" to new pull request'
author: 'Shantanu Pawar'


inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    

runs:
  using: 'node12'
  main: 'dist/index.js'

